-- scripts sql ---

-- tabla TAZA---
CREATE TABLE TAZA (
 PK_TAZA INTEGER NOT NULL,
 TIPO VARCHAR(25) NOT NULL,
 COLOR VARCHAR(100) NOT NULL,
 DIMENSIONES VARCHAR(25) NOT NULL,
 CAPACIDAD VARCHAR(25) NOT NULL,
 MODELO VARCHAR(25) NOT NULL,
 MATERIAL VARCHAR(25) NOT NULL,
 PRECIO DOUBLE NOT NULL,
 STOCK INTEGER NOT NULL,
 CONSTRAINT PANGEA.PK_CT_TAZA PRIMARY KEY( PK_TAZA ));
 
 
GRANT INSERT, SELECT, UPDATE, DELETE  
ON TAZA TO PUBLIC;

 
 --- tabla Pedido---
 CREATE TABLE PEDIDO (
 PK_PEDIDO INTEGER NOT NULL,
 FK_TAZA INTEGER NOT NULL, 
 NUM_PEDIDO INTEGER NOT NULL,
 CANTIDAD INTEGER NOT NULL,
 TOTAL DOUBLE NOT NULL,
 CONSTRAINT  PK_CT_PEDIDO PRIMARY KEY( PK_PEDIDO ));

ALTER TABLE PEDIDO 
	ADD CONSTRAINT  TAZA_PEDIDO
	FOREIGN KEY( FK_TAZA ) 
	REFERENCES PANGEA.TAZA ( PK_TAZA ) 
	ON DELETE RESTRICT 
	ON UPDATE NO ACTION ; 
	
 GRANT INSERT, SELECT, UPDATE, DELETE  
ON PEDIDO TO PUBLIC;

----- Insercion de registros para pruebas ----
 
INSERT INTO TAZA (PK_TAZA, TIPO, COLOR, DIMENSIONES,  CAPACIDAD, MODELO, MATERIAL, PRECIO, STOCK) 
VALUES (1, 'ALTA', 'ROJO / AZUL ', '15*20*30', '150 ML', '1500', 'CERAMICA', 150, 10);

INSERT INTO TAZA (PK_TAZA, TIPO, COLOR, DIMENSIONES,  CAPACIDAD, MODELO, MATERIAL, PRECIO, STOCK) 
VALUES (2, 'BAJA', 'VERDE / AMARILLO ', '15*15*15', '100 ML', '2000', 'CERAMICA', 100, 5);